// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Weather API
//
//	API для получения информации о текущей погоде.
//	Schemes:
//	  https
//	Host: localhost:8080
//	BasePath: /v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
