// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetWeatherForecast30daysOKCode is the HTTP code returned for type GetWeatherForecast30daysOK
const GetWeatherForecast30daysOKCode int = 200

/*
GetWeatherForecast30daysOK Успешный ответ с прогнозом погоды на 30 дней

swagger:response getWeatherForecast30daysOK
*/
type GetWeatherForecast30daysOK struct {

	/*
	  In: Body
	*/
	Payload *GetWeatherForecast30daysOKBody `json:"body,omitempty"`
}

// NewGetWeatherForecast30daysOK creates GetWeatherForecast30daysOK with default headers values
func NewGetWeatherForecast30daysOK() *GetWeatherForecast30daysOK {

	return &GetWeatherForecast30daysOK{}
}

// WithPayload adds the payload to the get weather forecast30days o k response
func (o *GetWeatherForecast30daysOK) WithPayload(payload *GetWeatherForecast30daysOKBody) *GetWeatherForecast30daysOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get weather forecast30days o k response
func (o *GetWeatherForecast30daysOK) SetPayload(payload *GetWeatherForecast30daysOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWeatherForecast30daysOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWeatherForecast30daysBadRequestCode is the HTTP code returned for type GetWeatherForecast30daysBadRequest
const GetWeatherForecast30daysBadRequestCode int = 400

/*
GetWeatherForecast30daysBadRequest Неверный запрос

swagger:response getWeatherForecast30daysBadRequest
*/
type GetWeatherForecast30daysBadRequest struct {
}

// NewGetWeatherForecast30daysBadRequest creates GetWeatherForecast30daysBadRequest with default headers values
func NewGetWeatherForecast30daysBadRequest() *GetWeatherForecast30daysBadRequest {

	return &GetWeatherForecast30daysBadRequest{}
}

// WriteResponse to the client
func (o *GetWeatherForecast30daysBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetWeatherForecast30daysInternalServerErrorCode is the HTTP code returned for type GetWeatherForecast30daysInternalServerError
const GetWeatherForecast30daysInternalServerErrorCode int = 500

/*
GetWeatherForecast30daysInternalServerError Внутренняя ошибка сервера

swagger:response getWeatherForecast30daysInternalServerError
*/
type GetWeatherForecast30daysInternalServerError struct {
}

// NewGetWeatherForecast30daysInternalServerError creates GetWeatherForecast30daysInternalServerError with default headers values
func NewGetWeatherForecast30daysInternalServerError() *GetWeatherForecast30daysInternalServerError {

	return &GetWeatherForecast30daysInternalServerError{}
}

// WriteResponse to the client
func (o *GetWeatherForecast30daysInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
