// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetWeatherForecast30daysHandlerFunc turns a function with the right signature into a get weather forecast30days handler
type GetWeatherForecast30daysHandlerFunc func(GetWeatherForecast30daysParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetWeatherForecast30daysHandlerFunc) Handle(params GetWeatherForecast30daysParams) middleware.Responder {
	return fn(params)
}

// GetWeatherForecast30daysHandler interface for that can handle valid get weather forecast30days params
type GetWeatherForecast30daysHandler interface {
	Handle(GetWeatherForecast30daysParams) middleware.Responder
}

// NewGetWeatherForecast30days creates a new http.Handler for the get weather forecast30days operation
func NewGetWeatherForecast30days(ctx *middleware.Context, handler GetWeatherForecast30daysHandler) *GetWeatherForecast30days {
	return &GetWeatherForecast30days{Context: ctx, Handler: handler}
}

/*
	GetWeatherForecast30days swagger:route GET /weather/forecast/30days getWeatherForecast30days

# Получить прогноз погоды на 30 дней

Возвращает прогноз погоды на 30 дней для заданного города.
*/
type GetWeatherForecast30days struct {
	Context *middleware.Context
	Handler GetWeatherForecast30daysHandler
}

func (o *GetWeatherForecast30days) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetWeatherForecast30daysParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetWeatherForecast30daysOKBody get weather forecast30days o k body
//
// swagger:model GetWeatherForecast30daysOKBody
type GetWeatherForecast30daysOKBody struct {

	// Название города
	City string `json:"city,omitempty"`

	// Прогноз на следующие 30 дней
	Forecast []*GetWeatherForecast30daysOKBodyForecastItems0 `json:"forecast"`
}

// Validate validates this get weather forecast30days o k body
func (o *GetWeatherForecast30daysOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateForecast(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWeatherForecast30daysOKBody) validateForecast(formats strfmt.Registry) error {
	if swag.IsZero(o.Forecast) { // not required
		return nil
	}

	for i := 0; i < len(o.Forecast); i++ {
		if swag.IsZero(o.Forecast[i]) { // not required
			continue
		}

		if o.Forecast[i] != nil {
			if err := o.Forecast[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getWeatherForecast30daysOK" + "." + "forecast" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getWeatherForecast30daysOK" + "." + "forecast" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get weather forecast30days o k body based on the context it is used
func (o *GetWeatherForecast30daysOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateForecast(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWeatherForecast30daysOKBody) contextValidateForecast(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Forecast); i++ {

		if o.Forecast[i] != nil {

			if swag.IsZero(o.Forecast[i]) { // not required
				return nil
			}

			if err := o.Forecast[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getWeatherForecast30daysOK" + "." + "forecast" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getWeatherForecast30daysOK" + "." + "forecast" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetWeatherForecast30daysOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWeatherForecast30daysOKBody) UnmarshalBinary(b []byte) error {
	var res GetWeatherForecast30daysOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// GetWeatherForecast30daysOKBodyForecastItems0 get weather forecast30days o k body forecast items0
//
// swagger:model GetWeatherForecast30daysOKBodyForecastItems0
type GetWeatherForecast30daysOKBodyForecastItems0 struct {

	// Дата прогноза
	// Format: date
	Date strfmt.Date `json:"date,omitempty"`

	// Краткое описание погоды
	Description string `json:"description,omitempty"`

	// Максимальная температура
	TemperatureMax float64 `json:"temperature_max,omitempty"`

	// Минимальная температура
	TemperatureMin float64 `json:"temperature_min,omitempty"`
}

// Validate validates this get weather forecast30days o k body forecast items0
func (o *GetWeatherForecast30daysOKBodyForecastItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWeatherForecast30daysOKBodyForecastItems0) validateDate(formats strfmt.Registry) error {
	if swag.IsZero(o.Date) { // not required
		return nil
	}

	if err := validate.FormatOf("date", "body", "date", o.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get weather forecast30days o k body forecast items0 based on context it is used
func (o *GetWeatherForecast30daysOKBodyForecastItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetWeatherForecast30daysOKBodyForecastItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetWeatherForecast30daysOKBodyForecastItems0) UnmarshalBinary(b []byte) error {
	var res GetWeatherForecast30daysOKBodyForecastItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
