// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetWeatherOKCode is the HTTP code returned for type GetWeatherOK
const GetWeatherOKCode int = 200

/*
GetWeatherOK Успешный ответ с данными о погоде

swagger:response getWeatherOK
*/
type GetWeatherOK struct {

	/*
	  In: Body
	*/
	Payload *GetWeatherOKBody `json:"body,omitempty"`
}

// NewGetWeatherOK creates GetWeatherOK with default headers values
func NewGetWeatherOK() *GetWeatherOK {

	return &GetWeatherOK{}
}

// WithPayload adds the payload to the get weather o k response
func (o *GetWeatherOK) WithPayload(payload *GetWeatherOKBody) *GetWeatherOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get weather o k response
func (o *GetWeatherOK) SetPayload(payload *GetWeatherOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWeatherOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWeatherBadRequestCode is the HTTP code returned for type GetWeatherBadRequest
const GetWeatherBadRequestCode int = 400

/*
GetWeatherBadRequest Неверный запрос

swagger:response getWeatherBadRequest
*/
type GetWeatherBadRequest struct {
}

// NewGetWeatherBadRequest creates GetWeatherBadRequest with default headers values
func NewGetWeatherBadRequest() *GetWeatherBadRequest {

	return &GetWeatherBadRequest{}
}

// WriteResponse to the client
func (o *GetWeatherBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetWeatherInternalServerErrorCode is the HTTP code returned for type GetWeatherInternalServerError
const GetWeatherInternalServerErrorCode int = 500

/*
GetWeatherInternalServerError Внутренняя ошибка сервера

swagger:response getWeatherInternalServerError
*/
type GetWeatherInternalServerError struct {
}

// NewGetWeatherInternalServerError creates GetWeatherInternalServerError with default headers values
func NewGetWeatherInternalServerError() *GetWeatherInternalServerError {

	return &GetWeatherInternalServerError{}
}

// WriteResponse to the client
func (o *GetWeatherInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
