// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetWeatherForecast7daysOKCode is the HTTP code returned for type GetWeatherForecast7daysOK
const GetWeatherForecast7daysOKCode int = 200

/*
GetWeatherForecast7daysOK Успешный ответ с прогнозом погоды на 7 дней

swagger:response getWeatherForecast7daysOK
*/
type GetWeatherForecast7daysOK struct {

	/*
	  In: Body
	*/
	Payload *GetWeatherForecast7daysOKBody `json:"body,omitempty"`
}

// NewGetWeatherForecast7daysOK creates GetWeatherForecast7daysOK with default headers values
func NewGetWeatherForecast7daysOK() *GetWeatherForecast7daysOK {

	return &GetWeatherForecast7daysOK{}
}

// WithPayload adds the payload to the get weather forecast7days o k response
func (o *GetWeatherForecast7daysOK) WithPayload(payload *GetWeatherForecast7daysOKBody) *GetWeatherForecast7daysOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get weather forecast7days o k response
func (o *GetWeatherForecast7daysOK) SetPayload(payload *GetWeatherForecast7daysOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetWeatherForecast7daysOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetWeatherForecast7daysBadRequestCode is the HTTP code returned for type GetWeatherForecast7daysBadRequest
const GetWeatherForecast7daysBadRequestCode int = 400

/*
GetWeatherForecast7daysBadRequest Неверный запрос

swagger:response getWeatherForecast7daysBadRequest
*/
type GetWeatherForecast7daysBadRequest struct {
}

// NewGetWeatherForecast7daysBadRequest creates GetWeatherForecast7daysBadRequest with default headers values
func NewGetWeatherForecast7daysBadRequest() *GetWeatherForecast7daysBadRequest {

	return &GetWeatherForecast7daysBadRequest{}
}

// WriteResponse to the client
func (o *GetWeatherForecast7daysBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetWeatherForecast7daysInternalServerErrorCode is the HTTP code returned for type GetWeatherForecast7daysInternalServerError
const GetWeatherForecast7daysInternalServerErrorCode int = 500

/*
GetWeatherForecast7daysInternalServerError Внутренняя ошибка сервера

swagger:response getWeatherForecast7daysInternalServerError
*/
type GetWeatherForecast7daysInternalServerError struct {
}

// NewGetWeatherForecast7daysInternalServerError creates GetWeatherForecast7daysInternalServerError with default headers values
func NewGetWeatherForecast7daysInternalServerError() *GetWeatherForecast7daysInternalServerError {

	return &GetWeatherForecast7daysInternalServerError{}
}

// WriteResponse to the client
func (o *GetWeatherForecast7daysInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
